version: '3.8'
networks:
  default:
    name: slab2reuse_network
    driver: bridge
services:
  postgres:
    image: postgres:15
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: slab2reuse_database
    ports:
      - "5430:5432"
    volumes: 
      - ./database/data:/var/lib/postgresql/data
    networks:
      - default
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/slab2reuse_database
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres_data: