export enum MaterialKeyType {
  Id = 'materialId',
  CrossSectionId = 'materialCrossSectionId',
  BuildingId = 'materialBuildingId',
  MaterialCategory = 'materialMaterialCategory',
  CompressiveStrength = 'materialCompressiveStrength',
  TensileStrength = 'materialTensileStrength',
  ElasticModulus = 'materialElasticModulus',
  Density = 'materialDensity',
  ExposureClass = 'materialExposureClass',
  Fc0k = 'materialFc0k',
  Ft0k = 'materialFt0k',
  Fc90k = 'materialFc90k',
  Ft90k = 'materialFt90k',
}
