import { VisualCondition } from '../enums/visualCondition';
import { SlabType } from '../types/slabType';

export const exampleData: SlabType[] = [
  {
    id: '0',
    planReference: 'U-Y/1-8',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 4800,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '1',
    planReference: 'U-Y/9-16',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 4800,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '2',
    planReference: 'U-Y/21-24',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 2400,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '3',
    planReference: 'U-Y/25-32',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 4800,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '4',
    planReference: 'U-Y/33-40',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 4800,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '5',
    planReference: 'U-Y/41-44',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 2400,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '6',
    planReference: 'U-Y/49-52',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 2400,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '7',
    planReference: 'U-Y/53-60',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 4800,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '8',
    planReference: 'U-Y/61-68',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 4800,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '9',
    planReference: 'U-Y/69-72',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 2400,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '10',
    planReference: 'U-Y/77-84',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 4800,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '11',
    planReference: 'U-Y/85-92',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 4800,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '12',
    planReference: 'Q-T/1-8',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 4800,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '13',
    planReference: 'Q-T/9-16',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 4800,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '14',
    planReference: 'Q-T/21-24',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 2400,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '15',
    planReference: 'Q-T/25-32',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 4800,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '16',
    planReference: 'Q-T/33-40',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 4800,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '17',
    planReference: 'Q-T/41-44',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 2400,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '18',
    planReference: 'Q-T/49-52',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 2400,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '19',
    planReference: 'Q-T/53-60',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 4800,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '20',
    planReference: 'Q-T/61-68',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 4800,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '21',
    planReference: 'Q-T/69-72',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 2400,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '22',
    planReference: 'Q-T/77-84',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 4800,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '23',
    planReference: 'Q-T/85-92',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 4800,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '24',
    planReference: 'M-P/1-6',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '25',
    planReference: 'M-P/7-12',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '26',
    planReference: 'O-P/3-18',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 1188,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 4,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '27',
    planReference: 'O-P/19-24',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 1188,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 4,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '28',
    planReference: 'M-P/25-32',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 4800,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '29',
    planReference: 'M-P/33-40',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 4800,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '30',
    planReference: 'O-P/41-46',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 1188,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 4,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '31',
    planReference: 'O-P/47-52',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 1188,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 4,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '32',
    planReference: 'M-P/53-60',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 4800,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '33',
    planReference: 'M-P/61-68',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 4800,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '34',
    planReference: 'O-P/69-74',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 1188,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 4,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '35',
    planReference: 'O-P/75-80',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 1188,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 4,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '36',
    planReference: 'M-P/81-86',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '37',
    planReference: 'M-P/87-92',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '38',
    planReference: 'I-L/1-6',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '39',
    planReference: 'I-L/7-12',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '40',
    planReference: 'I-N/13-15',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 1777,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 6,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '41',
    planReference: 'I-N/16-18',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 1777,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 6,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '42',
    planReference: 'I-N/19-21',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 1777,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 6,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '43',
    planReference: 'I-N/22-24',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 1777,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 6,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '44',
    planReference: 'I-L/25-32',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 4800,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '45',
    planReference: 'I-L/33-40',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 4800,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '46',
    planReference: 'I-N/41-44',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 1777,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 6,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '47',
    planReference: 'I-N/44-46',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 1777,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 6,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '48',
    planReference: 'I-N/47-49',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 1777,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 6,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '49',
    planReference: 'I-N/50-52',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 1777,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 6,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '50',
    planReference: 'I-L/53-60',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 4800,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '51',
    planReference: 'I-L/61-68',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 4800,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '52',
    planReference: 'I-N/69-71',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 1777,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 6,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '53',
    planReference: 'I-N/72-74',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 1777,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 6,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '54',
    planReference: 'I-N/75-77',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 1777,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 6,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '55',
    planReference: 'I-N/78-80',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 1777,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 6,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '56',
    planReference: 'I-L/81-86',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '57',
    planReference: 'I-L/87-92',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '58',
    planReference: 'E-H/1-6',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '59',
    planReference: 'E-H/7-12',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '60',
    planReference: 'E-H/13-18',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '61',
    planReference: 'E-H/19-24',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '62',
    planReference: 'E-H/25-32',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 4800,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '63',
    planReference: 'E-H/33-40',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 4800,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '64',
    planReference: 'E-H/41-46',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '65',
    planReference: 'E-H/47-52',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '66',
    planReference: 'E-H/53-60',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 4800,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '67',
    planReference: 'E-H/61-68',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 4800,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '68',
    planReference: 'E-H/69-74',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '69',
    planReference: 'E-H/75-80',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '70',
    planReference: 'E-H/81-86',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '71',
    planReference: 'E-H/87-92',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '72',
    planReference: 'A-D/1-6',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '73',
    planReference: 'A-D/7-12',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '74',
    planReference: 'A-D/13-18',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '75',
    planReference: 'A-D/19-24',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '76',
    planReference: 'A-D/25-32',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 4800,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '77',
    planReference: 'A-D/33-40',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 4800,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '78',
    planReference: 'A-D/41-46',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '79',
    planReference: 'A-D/47-52',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '80',
    planReference: 'A-D/53-60',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 4800,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '81',
    planReference: 'A-D/61-68',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 4800,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '82',
    planReference: 'A-D/69-74',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '83',
    planReference: 'A-D/75-80',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '84',
    planReference: 'A-D/81-86',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
  {
    id: '85',
    planReference: 'A-D/87-92',
    location_x: 2400,
    location_y: 13200,
    floor: 1,
    strength: 'C25 / 30',
    dimensions_l: 3600,
    dimensions_w: 2377,
    dimensions_h: 180,
    liveload: 2,
    typeOfElement: 'HC',
    rebarDiameterTop: 12.5,
    rebarAmountTop: 0,
    rebarDiameterBottom: 12.5,
    rebarAmountBottom: 8,
    reboundTestData: [],
    condition: VisualCondition.Good,
    rotZAxis_yaw: 0,
  },
];
