name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build frontend service
        run: docker compose build frontend

      - name: Build backend service
        run: docker compose build backend

      - name: Build database service
        run: docker compose build database

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "Host target-host" > ~/.ssh/config
          echo "  HostName ${{ secrets.MAC_MINI_HOST }}" >> ~/.ssh/config
          echo "  User ${{ secrets.MAC_MINI_USER }}" >> ~/.ssh/config
          echo "  IdentitiesOnly yes" >> ~/.ssh/config
          echo "  IdentityAgent \$SSH_AUTH_SOCK" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
        
      - name: Deploy to Mac mini
        run: |
          ssh target-host << 'EOF'
            cd /Users/slab2reuse/projects/Slab2Reuse
            git pull origin main
            docker compose down
            docker compose build
            docker compose up -d
          EOF
